name: noisereduce
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6
  - notebook>5.2
  # scipy is optional - install with: pip install noisereduce[scipy]
  - numpy
  - tqdm
  - pip:
     - noisereduce
